# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: "@SchezHugo", password: "carajo", balance: 200)
User.create(username: "@Pascual", password: "carajo", balance: 200)
User.create(username: "@Pepito", password: "carajo", balance: 200)
User.create(username: "@Menganito", password: "carajo", balance: 200)

b1 = Business.create(name: "@ThePub", password: "carajo", balance: 100)
b2 = Business.create(name: "@TheBarberShop", password: "carajo", balance: 100)
b3 = Business.create(name: "@TheClub", password: "carajo", balance: 100)
b4 = Business.create(name: "@TheBigBurger", password: "carajo", balance: 100)


b1.create_transaction("@Pascual", 20)
b1.create_transaction("@Pascual", 10)
b1.create_transaction("@Pascual", 10)
b1.create_transaction("@Pepito", 10)
b1.create_transaction("@Pepito", 5)
b1.create_transaction("@Pepito", 5)

b2.create_transaction("@Pascual", 5)
b2.create_transaction("@Pascual", 5)
b2.create_transaction("@Pascual", 5)
b2.create_transaction("@Pepito", 5)
b2.create_transaction("@Pepito", 5)
b2.create_transaction("@Pepito", 5)
b2.create_transaction("@SchezHugo", 7)
b2.create_transaction("@SchezHugo", 7)
b2.create_transaction("@SchezHugo", 7)
b2.create_transaction("@Menganito", 2)
b2.create_transaction("@Menganito", 2)
b2.create_transaction("@Menganito", 2)
b2.create_transaction("@Pascual", 5)

b3.create_transaction("@Pascual", 5)
b3.create_transaction("@Pascual", 5)
b3.create_transaction("@Pascual", 2)
b3.create_transaction("@Pepito", 5)
b3.create_transaction("@Pepito", 5)
b3.create_transaction("@Pepito", 5)
b3.create_transaction("@SchezHugo", 7)
b3.create_transaction("@SchezHugo", 10)
b3.create_transaction("@SchezHugo", 7)
b3.create_transaction("@Menganito", 2)
b3.create_transaction("@Menganito", 2)
b3.create_transaction("@Menganito", 2)
b3.create_transaction("@Pascual", 5)

b4.create_transaction("@Pascual", 5)
b4.create_transaction("@Pascual", 10)
b4.create_transaction("@Pascual", 2)
b4.create_transaction("@Pepito", 5)
b4.create_transaction("@Pepito", 5)
b4.create_transaction("@Pepito", 5)
b4.create_transaction("@SchezHugo", 10)
b4.create_transaction("@SchezHugo", 10)
b4.create_transaction("@SchezHugo", 7)
b4.create_transaction("@Menganito", 2)
b4.create_transaction("@Menganito", 2)
b4.create_transaction("@Menganito", 2)
b4.create_transaction("@Pascual", 5)


Item.create(name: "Pint - Beer A", price: 3.25, business_id: 1)
Item.create(name: "Pint - Beer B", price: 2.25, business_id: 1)
Item.create(name: "Pint - Beer C", price: 4.25, business_id: 1)
Item.create(name: "Pint - Beer D", price: 3.65, business_id: 1)
Item.create(name: "Pint - Beer E", price: 5.25, business_id: 1)
Item.create(name: "Pint - Beer F", price: 3.75, business_id: 1)
Item.create(name: "Pint - Beer G", price: 2.95, business_id: 1)
Item.create(name: "Pint - Beer H", price: 3.25, business_id: 1)


Item.create(name: "Traditional Hair Cut", price: 13.25, business_id: 2)
Item.create(name: "Hair cut B", price: 22.25, business_id: 2)
Item.create(name: "Hair cut C", price: 14.25, business_id: 2)
Item.create(name: "Hair cut D", price: 13.65, business_id: 2)
Item.create(name: "Hair cut E", price: 15.25, business_id: 2)
Item.create(name: "Hair cut F", price: 13.75, business_id: 2)
Item.create(name: "Hair cut G", price: 12.95, business_id: 2)

Item.create(name: "Friday Sessions", price: 23.25, business_id: 3)
Item.create(name: "Saturday Seesions", price: 33.35, business_id: 3)
Item.create(name: "Ain't no Sunday Morinings", price: 24.35, business_id: 3)
Item.create(name: "Whiskey", price: 13.65, business_id: 3)
Item.create(name: "Rhum", price: 15.35, business_id: 3)
Item.create(name: "Vodka", price: 13.75, business_id: 3)
Item.create(name: "Gin", price: 13.95, business_id: 3)

Item.create(name: "Big Burger Classic", price: 13.25, business_id: 4)
Item.create(name: "Big Burger XXL", price: 12.25, business_id: 4)
Item.create(name: "Baconator", price: 14.25, business_id: 4)
Item.create(name: "Big Burger Chicken Burguer", price: 13.65, business_id: 4)
Item.create(name: "Big Farm Burger", price: 15.25, business_id: 4)
Item.create(name: "Big Veggie Burger", price: 13.75, business_id: 4)
Item.create(name: "Big Vengan Burger", price: 12.95, business_id: 4)
